-- Run once in Supabase Dashboard → SQL Editor for project qfgplzxniceqcmptumxs.
-- The site only uses the public anon key. RLS keeps game names and answers
-- private; only anonymous job-vote counts are readable.

create extension if not exists pgcrypto;

create table if not exists public.career_ladder_games (
  id uuid primary key,
  nickname text not null check (char_length(nickname) between 1 and 50),
  submitted_job text not null check (char_length(submitted_job) between 1 and 80),
  normalized_job text not null check (char_length(normalized_job) between 1 and 80),
  outcome text not null check (outcome in ('guessed', 'player_won')),
  question_count integer not null check (question_count between 0 and 300),
  answers jsonb not null default '[]'::jsonb check (jsonb_typeof(answers) = 'array'),
  elapsed_seconds integer not null check (elapsed_seconds between 0 and 3600),
  created_at timestamptz not null default now()
);

alter table public.career_ladder_games enable row level security;
revoke all on public.career_ladder_games from anon, authenticated;
-- PostgREST needs the table-level SELECT privilege to finish its insert-count
-- query even with return=minimal. No SELECT RLS policy is created, so rows
-- remain unreadable from the public API.
grant insert, select on public.career_ladder_games to anon, authenticated;

drop policy if exists "Public can submit game runs" on public.career_ladder_games;
create policy "Public can submit game runs"
  on public.career_ladder_games for insert to anon, authenticated
  with check (true);

create table if not exists public.career_ladder_job_votes (
  id bigint generated by default as identity primary key,
  job_key text not null check (char_length(job_key) between 1 and 80),
  voter_id uuid not null,
  created_at timestamptz not null default now(),
  constraint career_ladder_job_votes_one_per_visitor unique (job_key, voter_id)
);

alter table public.career_ladder_job_votes enable row level security;
revoke all on public.career_ladder_job_votes from anon, authenticated;
grant insert, select on public.career_ladder_job_votes to anon, authenticated;
grant usage, select on sequence public.career_ladder_job_votes_id_seq to anon, authenticated;

drop policy if exists "Public can submit job votes" on public.career_ladder_job_votes;
create policy "Public can submit job votes"
  on public.career_ladder_job_votes for insert to anon, authenticated
  with check (true);

drop policy if exists "Public can count job votes" on public.career_ladder_job_votes;
create policy "Public can count job votes"
  on public.career_ladder_job_votes for select to anon, authenticated
  using (true);

create index if not exists career_ladder_games_created_at_idx
  on public.career_ladder_games (created_at desc);
create index if not exists career_ladder_votes_job_key_idx
  on public.career_ladder_job_votes (job_key);

