(() => {
  const $ = (id) => document.getElementById(id);
  const config = window.CAREER_LADDER_CONFIG || {};
  const supabaseReady = Boolean(config.supabaseUrl && config.supabaseAnonKey);
  const choiceLabels = ["Yes", "No", "I don't know", "Probably", "Probably not"];
  const bank = [];
  const add = (text, tags) => bank.push({ text, tags });
  const dimensions = [
    ["people", "Do you spend a lot of your workday helping or serving people?", ["teacher","nurse","doctor","therapist","social worker","dentist","vet","coach","chef","barista","retail worker","customer support","hairdresser","police officer","firefighter","lawyer","recruiter","personal trainer","flight attendant","photographer"]],
    ["create", "Do you make, design, or create things as part of your job?", ["designer","artist","writer","architect","chef","photographer","musician","filmmaker","developer","marketing manager","carpenter","fashion designer","game developer","florist","baker","journalist","illustrator","interior designer","content creator","engineer"]],
    ["numbers", "Do you work with numbers, budgets, or financial records often?", ["accountant","data analyst","financial analyst","economist","banker","actuary","auditor","business analyst","developer","engineer","project manager","real estate agent","scientist","statistician","trader","bookkeeper","consultant","pharmacist","architect","supply chain manager"]],
    ["outdoors", "Do you regularly work outdoors or away from a desk?", ["farmer","construction worker","electrician","plumber","landscaper","delivery driver","pilot","police officer","firefighter","paramedic","photographer","park ranger","geologist","architect","carpenter","roofer","fisher","mechanic","surveyor","postal worker"]],
    ["care", "Does your job involve caring for someone's health or wellbeing?", ["doctor","nurse","therapist","dentist","vet","pharmacist","paramedic","social worker","caregiver","personal trainer","teacher","counselor","nutritionist","midwife","optometrist","occupational therapist","physical therapist","psychologist","firefighter","coach"]],
    ["tech", "Do you use computers or technology as a core part of your job?", ["developer","IT support specialist","data analyst","designer","engineer","cybersecurity analyst","product manager","scientist","accountant","architect","marketing manager","writer","video editor","game developer","UX researcher","business analyst","teacher","pilot","journalist","systems administrator"]],
    ["lead", "Are you responsible for leading a team or making important decisions?", ["manager","principal","doctor","lawyer","chef","project manager","business owner","engineering manager","police officer","creative director","recruiter","consultant","product manager","school principal","executive","construction manager","producer","team lead","real estate agent","pilot"]],
    ["study", "Does your job usually require specialist training or a degree?", ["doctor","lawyer","teacher","engineer","architect","scientist","accountant","pharmacist","therapist","nurse","pilot","dentist","economist","data analyst","journalist","veterinarian","psychologist","recruiter","designer","urban planner"]],
    ["move", "Are you on your feet or physically active for much of the day?", ["nurse","chef","construction worker","electrician","plumber","delivery driver","farmer","firefighter","police officer","barista","retail worker","dancer","athlete","personal trainer","flight attendant","mechanic","caregiver","carpenter","hairdresser","paramedic"]],
    ["words", "Do you write, explain, or communicate with words a lot at work?", ["writer","journalist","teacher","lawyer","marketing manager","recruiter","customer support","translator","copywriter","public relations specialist","librarian","consultant","therapist","social worker","editor","scientist","salesperson","politician","technical writer","podcaster"]],
    ["build", "Do you build, fix, or maintain physical things?", ["engineer","construction worker","electrician","plumber","carpenter","mechanic","architect","technician","roofer","welder","IT support specialist","landscaper","facilities manager","builder","machinist","auto mechanic","solar installer","painter","survey technician","manufacturing worker"]],
    ["sell", "Is selling, persuading, or finding customers part of your job?", ["salesperson","real estate agent","recruiter","marketing manager","business owner","fundraiser","insurance agent","account executive","car salesperson","financial advisor","public relations specialist","retail worker","consultant","travel agent","brand manager","jeweler","investment banker","event planner","business development manager","auctioneer"]],
    ["science", "Do you investigate, test, or research things as a regular part of work?", ["scientist","data analyst","doctor","journalist","UX researcher","engineer","detective","market researcher","economist","environmental scientist","lab technician","geologist","auditor","historian","psychologist","chemist","biologist","archaeologist","quality analyst","epidemiologist"]],
    ["food", "Do you prepare, serve, or grow food for work?", ["chef","farmer","baker","barista","restaurant manager","food scientist","nutritionist","butcher","fisher","food truck owner","pastry chef","brewer","sommelier","caterer","line cook","grocer","florist","agricultural engineer","food photographer","dietitian"]],
    ["transport", "Do you drive, fly, or otherwise transport people or goods?", ["pilot","delivery driver","truck driver","bus driver","flight attendant","train operator","sailor","courier","taxi driver","logistics manager","air traffic controller","ship captain","postal worker","rideshare driver","rail engineer","bicycle messenger","paramedic","chauffeur","warehouse manager","travel agent"]],
    ["teach", "Do you teach, train, or coach other people?", ["teacher","coach","professor","tutor","personal trainer","corporate trainer","music teacher","driving instructor","librarian","mentor","nurse","therapist","fitness instructor","school principal","swim instructor","dance teacher","consultant","recruiter","camp counselor","technical instructor"]],
    ["law", "Do you work with laws, rules, or public safety?", ["lawyer","police officer","judge","paralegal","firefighter","security guard","compliance officer","border officer","detective","social worker","politician","court reporter","insurance investigator","legal secretary","correctional officer","regulator","mediator","military officer","safety inspector","bailiff"]],
    ["media", "Do you create or work with media, art, or entertainment?", ["artist","writer","musician","filmmaker","photographer","journalist","video editor","actor","designer","game developer","illustrator","producer","podcaster","animator","dancer","sound engineer","content creator","curator","fashion designer","camera operator"]],
    ["independent", "Do you work for yourself or run your own business?", ["business owner","freelancer","consultant","artist","writer","photographer","real estate agent","farmer","chef","developer","designer","hairdresser","personal trainer","tradesperson","tutor","podcaster","filmmaker","florist","accountant","therapist"]],
    ["office", "Do you usually work in an office or a desk-based setting?", ["accountant","lawyer","developer","data analyst","recruiter","manager","architect","writer","designer","financial analyst","project manager","marketing manager","business analyst","journalist","consultant","economist","product manager","librarian","systems administrator","insurance agent"]],
  ];
  const questionVariants = {
    people:["Is helping or serving people a big part of your work?","Do people regularly come to you for help on the job?","Are conversations with customers, clients, or patients part of most workdays?","Would your job feel very different without direct contact with people?","Do you spend much of the day listening to or assisting someone?"],
    create:["Do you make or design something as part of your work?","Does your job leave room for creative decisions?","Do you often turn an idea into something original?","Is creating content, art, or a design part of your role?","Would coworkers describe your work as creative?"],
    numbers:["Do you regularly calculate, compare, or check figures at work?","Are budgets, prices, or financial records part of your job?","Do you use data to make work decisions?","Would a spreadsheet be useful in your normal workweek?","Do accurate calculations matter in your role?"],
    outdoors:["Do you spend a regular part of your workday outside?","Does your job take you to different places instead of one desk?","Do weather conditions affect how or where you work?","Would you describe your work setting as mostly outdoors?","Do you often travel between work sites?"],
    care:["Do you help people stay healthy or feel better?","Is someone's wellbeing part of your responsibility at work?","Do you provide care, guidance, or support to others?","Does your job involve responding to someone's health needs?","Would people come to you for help with their wellbeing?"],
    tech:["Do you use computers or specialist technology for core work tasks?","Would your job be difficult to do without digital tools?","Do you set up, build, repair, or analyze technology at work?","Is software a regular part of your workday?","Do you solve technical problems as part of your role?"],
    lead:["Do you make decisions that affect other people's work?","Are you responsible for guiding a team or project?","Do coworkers report to you or look to you for direction?","Do you set priorities for other people at work?","Does your role include managing a team, budget, or operation?"],
    study:["Did your job require specialist training or a qualification?","Do you rely on professional knowledge most people don't use daily?","Would someone need significant training before doing your job?","Are certifications, a license, or a degree important in your field?","Do you apply specialized expertise to solve work problems?"],
    move:["Are you on your feet for much of your working day?","Does your work involve lifting, moving, or physical activity?","Would you call your job physically active?","Do you move around more than you sit during a typical shift?","Is physical stamina useful for doing your work?"],
    words:["Do you write or explain things as a regular work task?","Are clear emails, reports, or presentations important in your role?","Do you spend much of the day talking, reading, or writing?","Do you help people understand information through words?","Is communication one of the main tools you use at work?"],
    build:["Do you build, repair, or maintain something physical?","Does your work involve tools, equipment, or materials?","Do you make sure buildings, machines, or systems keep working?","Would you describe your role as hands-on?","Do you install, assemble, or fix things for work?"],
    sell:["Do you help persuade people to buy, donate, or sign up?","Is finding customers or growing sales part of your job?","Do you promote a product, service, or idea at work?","Are negotiations or pitching part of your normal work?","Does your success depend partly on bringing in business?"],
    science:["Do you investigate questions or test ideas at work?","Do you collect evidence before drawing conclusions?","Does your job involve experiments, research, or analysis?","Do you look for patterns to explain how something works?","Is checking whether something is true a regular part of your role?"],
    food:["Do you prepare, serve, grow, or handle food at work?","Is food an important part of the product or service you provide?","Do you work in a kitchen, restaurant, farm, or food business?","Do you follow food safety or preparation steps on the job?","Would a customer associate your work with something to eat or drink?"],
    transport:["Do you help move people or goods from one place to another?","Is driving, flying, sailing, or routing part of your job?","Do you work with vehicles or transport systems?","Does your job involve planning or carrying out deliveries?","Are you responsible for getting someone or something safely to a destination?"],
    teach:["Do you teach, coach, or train people as part of your role?","Do you help others learn a skill or subject?","Do you give lessons, demonstrations, or feedback at work?","Would people describe you as an instructor or mentor?","Is helping someone improve a regular part of your job?"],
    law:["Do you work with laws, regulations, or official rules?","Is public safety part of your work?","Do you help enforce rules or make sure people follow them?","Does your job involve legal cases, investigations, or compliance?","Do you help resolve disputes or protect people from harm?"],
    media:["Do you make or edit content for an audience?","Is entertainment, news, art, or media part of your work?","Do you work with cameras, sound, performance, or publishing?","Could people see, hear, or read something you created?","Is storytelling or presenting ideas part of your job?"],
    independent:["Do you work for yourself or own a business?","Can you choose your own clients or projects?","Are you responsible for finding your own customers?","Do you invoice clients or run an independent practice?","Is your work not tied to one long-term employer?"],
    office:["Do you usually work at a desk or in an office?","Are most workdays spent in one indoor workplace?","Do you mainly handle information rather than physical materials?","Is a computer workstation where you do most of your work?","Do you usually work indoors in a fixed location?"]
  };
  for (const [tag, prompt] of dimensions) {
    add(prompt, [tag]);
    for (const wording of questionVariants[tag]) add(wording, [tag]);
  }
  const jobs = [...new Set(dimensions.flatMap(d => d[2]))];
  const candidates = jobs.map((name, i) => ({name, tags: new Set(dimensions.filter(d=>d[2].includes(name)).map(d=>d[0])), prior: 1 + (i % 3)}));
  let state = {phase:'intro', asked:[], askedTags:[], answers:[], history:[], pool:[...candidates], weights:{}, start:0, seconds:120, name:''};
  let timerId;
  let typingId = 0;
  const answerLikelihood = {"Yes":.88,"Probably":.69,"I don't know":.5,"Probably not":.31,"No":.12};
  function normalizeWeights(){const total=state.pool.reduce((sum,c)=>sum+(state.weights[c.name]||0),0);if(total>0)for(const c of state.pool)state.weights[c.name]=(state.weights[c.name]||0)/total}
  function updateBeliefs(tag,answer){const positive=answerLikelihood[answer];for(const candidate of state.pool){const old=state.weights[candidate.name]||0;const likelihood=answer==='I don\'t know'?.5:(candidate.tags.has(tag)?positive:1-positive);state.weights[candidate.name]=old*likelihood}normalizeWeights()}
  function chooseDimension(){const remaining=dimensions.filter(([tag])=>!state.askedTags.includes(tag));if(!remaining.length)return null;let winner=null,best=-1;for(const dimension of remaining){const [tag]=dimension;const chance=state.pool.reduce((sum,c)=>sum+(state.weights[c.name]||0)*(c.tags.has(tag)?1:0),0);const p=Math.max(.0001,Math.min(.9999,chance));const entropy=-(p*Math.log2(p)+(1-p)*Math.log2(1-p));const varied=entropy+Math.random()*.035;if(varied>best){best=varied;winner=dimension}}return winner}
  let soundOn=true,musicTrack='music-entry',musicTimer=null,audioContext=null,synthGain=null;
  function stopSynth(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}if(synthGain&&audioContext){try{synthGain.gain.setTargetAtTime(0,audioContext.currentTime,.04)}catch{}}}
  function unlockAudio(){try{const AudioAPI=window.AudioContext||window.webkitAudioContext;if(!AudioAPI)return;audioContext ||= new AudioAPI();if(audioContext.state==='suspended')audioContext.resume()}catch{}}
  function startSynth(track){stopSynth();unlockAudio();if(!soundOn||!audioContext)return;const songs={'music-entry':[261.63,329.63,392,523.25,392,329.63,293.66,349.23],'music-theme':[392,493.88,587.33,783.99,659.25,587.33,493.88,587.33],'music-happy':[523.25,659.25,783.99,1046.5,783.99,880,1046.5,1318.5],'music-sad':[293.66,349.23,392,349.23,293.66,261.63,220,261.63]};const notes=songs[track]||songs['music-entry'];try{audioContext.resume();synthGain=audioContext.createGain();synthGain.gain.value=.11;synthGain.connect(audioContext.destination);let beat=0;const playNote=()=>{if(!soundOn||!audioContext||!synthGain)return;const now=audioContext.currentTime,osc=audioContext.createOscillator(),env=audioContext.createGain();osc.type='triangle';osc.frequency.value=notes[beat++%notes.length];env.gain.setValueAtTime(.0001,now);env.gain.exponentialRampToValueAtTime(.32,now+.025);env.gain.exponentialRampToValueAtTime(.0001,now+.22);osc.connect(env);env.connect(synthGain);osc.start(now);osc.stop(now+.23)};playNote();musicTimer=setInterval(playNote,260)}catch{}}
  function setMusic(track){musicTrack=track;for(const a of document.querySelectorAll('audio')){a.pause();a.currentTime=0}stopSynth();if(!soundOn)return;const a=$(track);if(!a){startSynth(track);return}a.volume=.35;a.play().catch(()=>startSynth(track))}
  function expression(){const faces=['Let me dust off my tiny detective hat…','Ooh, I’m getting somewhere…','The ladder is doing some maths…','Your job is playing hard to get…','I have a very professional hunch…','Hmm. Suspiciously job-shaped…'];return faces[Math.floor(Math.random()*faces.length)]}
  function showIntro(){clearInterval(timerId);typingId++;$('start-button').disabled=false;$('stage-label').textContent='A LITTLE GAME ABOUT WHAT YOU DO';$('intro-copy').hidden=false;$('game-copy').hidden=true;$('timer').hidden=true;$('subtitle-overlay').textContent='';$('scene').classList.remove('zoomed');}
  function start(){if($('start-button').disabled)return;$('start-button').disabled=true;unlockAudio();state={phase:'intro',asked:[],askedTags:[],answers:[],history:[],pool:[...candidates],weights:Object.fromEntries(candidates.map(c=>[c.name,1/candidates.length])),start:Date.now(),seconds:120,name:''};$('stage-label').textContent='THE CAREER LADDER IS THINKING';setMusic('music-entry');$('scene').classList.add('zoomed');const words="Hope you don't have to hold your bladder cuz it's time for the Career Ladder".split(' ');const layer=$('subtitle-overlay');layer.replaceChildren();words.forEach((word,i)=>setTimeout(()=>{const span=document.createElement('span');span.textContent=(i?' ':'')+word;layer.append(span);},i*500));setTimeout(()=>{state.phase='hasjob';$('intro-copy').hidden=true;$('game-copy').hidden=false;layer.textContent='';renderQuestion('Do you have a job?','Be honest. The ladder can handle it.','hasjob');},words.length*500+500);}
  function pauseTimer(){clearInterval(timerId);timerId=null;}
  function runTimer(){pauseTimer();const paint=()=>{const m=String(Math.floor(state.seconds/60)).padStart(2,'0'),s=String(state.seconds%60).padStart(2,'0');$('timer').textContent=`${m}:${s}`};paint();timerId=setInterval(()=>{state.seconds--;paint();if(state.seconds<=0){pauseTimer();finishWin('The two minutes are up! You win. Tell me what you do?')}},1000)}
  function setAvatar(type){const avatar=$('asker-avatar');if(!avatar)return;avatar.className=`asker-avatar ${type}`;const labels={thinking:'Career Ladder asker thinking',curious:'Career Ladder asker curious',happy:'Career Ladder asker happy',sad:'Career Ladder asker sad',typing:'Career Ladder asker typing'};avatar.setAttribute('aria-label',labels[type]||labels.thinking)}
  function typeQuestion(prompt){const token=++typingId;const target=$('question');target.textContent='';$('answers').querySelectorAll('button').forEach(b=>b.disabled=true);setAvatar('typing');const dots=$('expression');dots.innerHTML='Thinking<span class="thinking-dots"><i>.</i><i>.</i><i>.</i></span>';let i=0;const typeNext=()=>{if(token!==typingId)return;if(i<prompt.length){target.textContent+=prompt[i++];setTimeout(typeNext,20)}else{$('answers').querySelectorAll('button').forEach(b=>b.disabled=false);setAvatar(state.phase==='guess'?'curious':state.phase==='stop'?'sad':'thinking');if(state.phase==='trait'||state.phase==='guess'){$('timer').hidden=false;runTimer()}}};typeNext()}
  function renderQuestion(prompt, helper='', type='trait'){pauseTimer();state.phase=type;setAvatar(type==='guess'?'curious':type==='stop'?'sad':'thinking');$('expression').textContent=type==='guess'?'I have a hunch…':expression();$('helper').textContent=helper;$('answers').replaceChildren();$('back-button').hidden=!state.history?.length||!['trait','guess'].includes(type);if(type==='name'){showForm();return}const choices=type==='hasjob'?['Yes','No']:type==='guess'?['Yes','No']:type==='stop'?[]:choiceLabels;for(const label of choices){const b=document.createElement('button');b.className='answer';b.textContent=label;b.onclick=()=>respond(label);$('answers').append(b)}$('progress-text').textContent=type==='hasjob'?'THE FIRST RUNG':`CLUE ${state.askedTags.length+1} OF ${dimensions.length} · ${bank.length} QUESTIONS READY`;$('progress-bar').style.width=`${Math.min(100,state.askedTags.length/dimensions.length*100)}%`;typeQuestion(prompt)}
  function goBack(){const previous=state.history.pop();if(!previous)return;pauseTimer();state.asked=previous.asked;state.askedTags=previous.askedTags;state.answers=previous.answers;state.pool=previous.pool;state.weights=previous.weights;state.current=previous.current;state.guess=previous.guess;state.lastGuessAt=previous.lastGuessAt;renderQuestion(previous.shownQuestion,'You can change your last answer.',previous.phase)}
  function showForm(){const form=document.createElement('form');form.className='share-form';form.innerHTML='<label>Your job<input name="job" required maxlength="80" placeholder="e.g. marine biologist"></label><label>Your name <span>(optional)</span><input name="name" maxlength="60" placeholder="What should I call you?"></label><button class="primary-button" type="submit">Help the next player <span>↗</span></button><button type="button" class="answer skip-share">Skip sharing</button><p class="form-note">Your job and name are saved only when the site owner configures Supabase. Don’t include anything private.</p>';form.onsubmit=(e)=>{e.preventDefault();const data=new FormData(form);saveContribution(String(data.get('job')).trim(),String(data.get('name')).trim());};form.querySelector('.skip-share').onclick=()=>endWin();$('answers').replaceChildren(form);}
  function saveHistory(phase){state.history.push({asked:[...state.asked],askedTags:[...state.askedTags],answers:[...state.answers],pool:[...state.pool],weights:{...state.weights},current:state.current,guess:state.guess,lastGuessAt:state.lastGuessAt,phase,shownQuestion:$('question').textContent})}
  function respond(label){pauseTimer();typingId++;if(state.phase==='hasjob'){if(label==='No'){setAvatar('sad');renderQuestion('Ahhh! You need a job for this.','Come back when you’ve got one!','stop');const b=document.createElement('button');b.className='primary-button';b.textContent='Try again';b.onclick=()=>{showIntro();};$('answers').append(b);setMusic('music-sad');return}renderQuestion('I’ll guess your job in two minutes.','If I guess it, you lose. If I don’t, you’ll make me cry. Ready?','ready');$('answers').replaceChildren();const b=document.createElement('button');b.className='primary-button';b.textContent='Let’s climb';b.onclick=()=>respond('Yes');$('answers').append(b);return}
    if(state.phase==='ready'){setMusic('music-theme');nextQuestion();return} if(state.phase==='guess'){if(label==='Yes'){finishLose();}else{saveHistory('guess');state.lastGuessAt=state.asked.length;state.weights[state.guess]=0;normalizeWeights();nextQuestion()}return}
    if(state.phase==='trait'){saveHistory('trait');state.asked.push(state.current.text);state.askedTags.push(state.current.tag);state.answers.push({question:state.current.text,answer:label,tag:state.current.tag});updateBeliefs(state.current.tag,label);learnedAnswers(state.current.text,label);nextQuestion();}}
  async function nextQuestion(){if(state.seconds<=0)return finishWin('The two minutes are up! You win. Tell me what you do?');
    if(supabaseReady&&state.answers.length>=4&&(state.lastGuessAt===undefined||state.asked.length>=state.lastGuessAt+2)){const learned=await supa('trusted_job_answers?select=job_name,job_normalized,question_text,answer_value,respondent_count,answer_count');if(learned){const scores=new Map();for(const row of learned){if(row.respondent_count<=3||row.answer_count<3)continue;const match=state.answers.some(a=>a.question===row.question_text&&a.answer===row.answer_value);if(match)scores.set(row.job_name,(scores.get(row.job_name)||0)+1)}const best=[...scores].sort((a,b)=>b[1]-a[1])[0];if(best&&best[1]>=3){state.guess=best[0];renderQuestion(`Is your job ${best[0]}?`,'More than three players taught me that one. Is it you?','guess');return}}}
    const sorted=[...state.pool].sort((a,b)=>(state.weights[b.name]||0)-(state.weights[a.name]||0));const top=sorted[0],first=state.weights[top?.name]||0,second=state.weights[sorted[1]?.name]||0;const earliestGuess=state.lastGuessAt===undefined?6:state.lastGuessAt+2;const confident=first>=.28&&first>=second*1.45;if(top&&state.asked.length>=earliestGuess&&(confident||state.asked.length>=12||state.seconds<15)){state.guess=top.name;renderQuestion(`Is your job ${top.name}?`,'The clues are lining up. Did I get it?','guess');return}if(state.askedTags.length>=dimensions.length){finishWin('Alright, you just win! Tell me what it is?');return}const dimension=chooseDimension();if(!dimension){finishWin('Alright, you just win! Tell me what it is?');return}const [tag]=dimension;const options=bank.filter(q=>q.tags.includes(tag)&&!state.asked.includes(q.text));const prompt=options[Math.floor(Math.random()*options.length)]||bank.find(q=>q.tags.includes(tag));state.current={text:prompt.text,tag};renderQuestion(prompt.text,'Choose the answer that fits best.');}
  function finishLose(){pauseTimer();state.phase='lose';$('timer').hidden=true;$('back-button').hidden=true;setAvatar('happy');$('stage-label').textContent='THE LADDER GOT THERE FIRST';$('expression').textContent='I knew it!';$('question').textContent=`You're a ${state.guess}!`;$('helper').textContent='The ladder wins this round. Fancy a rematch?';$('answers').replaceChildren();const b=document.createElement('button');b.className='primary-button';b.textContent='Play again';b.onclick=()=>showIntro();$('answers').append(b);setMusic('music-happy')}
  function finishWin(msg){pauseTimer();state.phase='name';$('timer').hidden=true;$('back-button').hidden=true;setAvatar('sad');$('stage-label').textContent='A JOB WELL DONE';$('expression').textContent='You got past me!';$('question').textContent=msg;$('helper').textContent='Tell me your job to teach the next ladder climber.';setMusic('music-sad');showForm()}
  function endWin(){pauseTimer();state.phase='done';$('back-button').hidden=true;$('stage-label').textContent='THANKS FOR PLAYING';$('expression').textContent='The ladder will remember this.';$('question').textContent='Thanks for climbing!';$('helper').textContent='Your answers were not saved. Come back for another round.';$('answers').replaceChildren();const b=document.createElement('button');b.className='primary-button';b.textContent='Play again';b.onclick=()=>showIntro();$('answers').append(b)}
  async function supa(path,method='GET',body,prefer='return=minimal'){if(!supabaseReady)return null;try{const r=await fetch(`${config.supabaseUrl.replace(/\/$/,'')}/rest/v1/${path}`,{method,headers:{apikey:config.supabaseAnonKey,Authorization:`Bearer ${config.supabaseAnonKey}`,...(body?{'Content-Type':'application/json','Prefer':prefer}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(`Supabase ${r.status}`);return r.status===204?[]:await r.json()}catch(e){console.warn('Career Ladder database is not connected:',e);return null}}
  async function learnedAnswers(question,answer){if(!supabaseReady)return;await supa('answer_history','POST',{question_text:question,answer_value:answer,session_id:sessionId});}
  const sessionId=crypto.randomUUID?.()||String(Date.now());
  const playerId=(()=>{try{let id=localStorage.getItem('career-ladder-player');if(!id){id=crypto.randomUUID?.()||String(Date.now())+Math.random();localStorage.setItem('career-ladder-player',id)}return id}catch{return crypto.randomUUID?.()||String(Date.now())}})();
  async function saveContribution(job,name){if(!supabaseReady){$('helper').textContent='Supabase is not connected yet, so I can’t save this. You can still play again!';const b=document.createElement('button');b.className='answer';b.textContent='Finish without saving';b.onclick=endWin;$('answers').append(b);return}const norm=job.toLowerCase().trim();await supa('job_suggestions?on_conflict=job_normalized,player_id','POST',{job_name:job,job_normalized:norm,player_id:playerId,player_name:name||null,answers:state.answers},'resolution=ignore-duplicates,return=minimal');const rows=await supa(`job_consensus?job_normalized=eq.${encodeURIComponent(norm)}&select=respondent_count`);const count=rows?.[0]?.respondent_count||0;$('question').textContent=count>3?'The ladder has learned a new job!':`Thanks! ${Math.max(0,4-count)} more player${4-count===1?'':'s'} needed before I can trust this job.`;$('helper').textContent='Your clue will help the next player. The game keeps the answers for future rounds.';state.phase='done';$('answers').replaceChildren();const b=document.createElement('button');b.className='primary-button';b.textContent='Play again';b.onclick=()=>showIntro();$('answers').append(b);setMusic('music-happy')}
  $('start-button').onclick=start;$('back-button').onclick=goBack;$('year').textContent=new Date().getFullYear();$('sound-toggle').onclick=()=>{soundOn=!soundOn;$('sound-toggle').innerHTML=soundOn?'♫ <span>Sound on</span>':'♫ <span>Sound off</span>';if(soundOn&&$('start-button').disabled){unlockAudio();setMusic(musicTrack)}else if(!soundOn){for(const a of document.querySelectorAll('audio'))a.pause();stopSynth()}};showIntro();
  // A 120-question wording bank feeds an adaptive picker that chooses the most useful unanswered work trait.
  window.CAREER_LADDER_QUESTION_COUNT=bank.length;
})();
