(() => {
  const $ = (id) => document.getElementById(id);
  const config = window.CAREER_LADDER_CONFIG || {};
  const supabaseReady = Boolean(config.supabaseUrl && config.supabaseAnonKey);
  const choiceLabels = ["Yes", "No", "I don't know", "Probably", "Probably not"];
  const bank = [];
  const add = (text, tags) => bank.push({ text, tags });
  const dimensions = [
    ["people", "Do you spend a lot of your workday helping or serving people?", ["teacher","nurse","doctor","therapist","social worker","dentist","vet","coach","chef","barista","retail worker","customer support","hairdresser","police officer","firefighter","lawyer","recruiter","personal trainer","flight attendant","photographer"]],
    ["create", "Do you make, design, or create things as part of your job?", ["designer","artist","writer","architect","chef","photographer","musician","filmmaker","developer","marketing manager","carpenter","fashion designer","game developer","florist","baker","journalist","illustrator","interior designer","content creator","engineer"]],
    ["numbers", "Do you work with numbers, budgets, or financial records often?", ["accountant","data analyst","financial analyst","economist","banker","actuary","auditor","business analyst","developer","engineer","project manager","real estate agent","scientist","statistician","trader","bookkeeper","consultant","pharmacist","architect","supply chain manager"]],
    ["outdoors", "Do you regularly work outdoors or away from a desk?", ["farmer","construction worker","electrician","plumber","landscaper","delivery driver","pilot","police officer","firefighter","paramedic","photographer","park ranger","geologist","architect","carpenter","roofer","fisher","mechanic","surveyor","postal worker"]],
    ["care", "Does your job involve caring for someone's health or wellbeing?", ["doctor","nurse","therapist","dentist","vet","pharmacist","paramedic","social worker","caregiver","personal trainer","teacher","counselor","nutritionist","midwife","optometrist","occupational therapist","physical therapist","psychologist","firefighter","coach"]],
    ["tech", "Do you use computers or technology as a core part of your job?", ["developer","IT support specialist","data analyst","designer","engineer","cybersecurity analyst","product manager","scientist","accountant","architect","marketing manager","writer","video editor","game developer","UX researcher","business analyst","teacher","pilot","journalist","systems administrator"]],
    ["lead", "Are you responsible for leading a team or making important decisions?", ["manager","principal","doctor","lawyer","chef","project manager","business owner","engineering manager","police officer","creative director","recruiter","consultant","product manager","school principal","executive","construction manager","producer","team lead","real estate agent","pilot"]],
    ["study", "Does your job usually require specialist training or a degree?", ["doctor","lawyer","teacher","engineer","architect","scientist","accountant","pharmacist","therapist","nurse","pilot","dentist","economist","data analyst","journalist","veterinarian","psychologist","recruiter","designer","urban planner"]],
    ["move", "Are you on your feet or physically active for much of the day?", ["nurse","chef","construction worker","electrician","plumber","delivery driver","farmer","firefighter","police officer","barista","retail worker","dancer","athlete","personal trainer","flight attendant","mechanic","caregiver","carpenter","hairdresser","paramedic"]],
    ["words", "Do you write, explain, or communicate with words a lot at work?", ["writer","journalist","teacher","lawyer","marketing manager","recruiter","customer support","translator","copywriter","public relations specialist","librarian","consultant","therapist","social worker","editor","scientist","salesperson","politician","technical writer","podcaster"]],
    ["build", "Do you build, fix, or maintain physical things?", ["engineer","construction worker","electrician","plumber","carpenter","mechanic","architect","technician","roofer","welder","IT support specialist","landscaper","facilities manager","builder","machinist","auto mechanic","solar installer","painter","survey technician","manufacturing worker"]],
    ["sell", "Is selling, persuading, or finding customers part of your job?", ["salesperson","real estate agent","recruiter","marketing manager","business owner","fundraiser","insurance agent","account executive","car salesperson","financial advisor","public relations specialist","retail worker","consultant","travel agent","brand manager","jeweler","investment banker","event planner","business development manager","auctioneer"]],
    ["science", "Do you investigate, test, or research things as a regular part of work?", ["scientist","data analyst","doctor","journalist","UX researcher","engineer","detective","market researcher","economist","environmental scientist","lab technician","geologist","auditor","historian","psychologist","chemist","biologist","archaeologist","quality analyst","epidemiologist"]],
    ["food", "Do you prepare, serve, or grow food for work?", ["chef","farmer","baker","barista","restaurant manager","food scientist","nutritionist","butcher","fisher","food truck owner","pastry chef","brewer","sommelier","caterer","line cook","grocer","florist","agricultural engineer","food photographer","dietitian"]],
    ["transport", "Do you drive, fly, or otherwise transport people or goods?", ["pilot","delivery driver","truck driver","bus driver","flight attendant","train operator","sailor","courier","taxi driver","logistics manager","air traffic controller","ship captain","postal worker","rideshare driver","rail engineer","bicycle messenger","paramedic","chauffeur","warehouse manager","travel agent"]],
    ["teach", "Do you teach, train, or coach other people?", ["teacher","coach","professor","tutor","personal trainer","corporate trainer","music teacher","driving instructor","librarian","mentor","nurse","therapist","fitness instructor","school principal","swim instructor","dance teacher","consultant","recruiter","camp counselor","technical instructor"]],
    ["law", "Do you work with laws, rules, or public safety?", ["lawyer","police officer","judge","paralegal","firefighter","security guard","compliance officer","border officer","detective","social worker","politician","court reporter","insurance investigator","legal secretary","correctional officer","regulator","mediator","military officer","safety inspector","bailiff"]],
    ["media", "Do you create or work with media, art, or entertainment?", ["artist","writer","musician","filmmaker","photographer","journalist","video editor","actor","designer","game developer","illustrator","producer","podcaster","animator","dancer","sound engineer","content creator","curator","fashion designer","camera operator"]],
    ["independent", "Do you work for yourself or run your own business?", ["business owner","freelancer","consultant","artist","writer","photographer","real estate agent","farmer","chef","developer","designer","hairdresser","personal trainer","tradesperson","tutor","podcaster","filmmaker","florist","accountant","therapist"]],
    ["office", "Do you usually work in an office or a desk-based setting?", ["accountant","lawyer","developer","data analyst","recruiter","manager","architect","writer","designer","financial analyst","project manager","marketing manager","business analyst","journalist","consultant","economist","product manager","librarian","systems administrator","insurance agent"]],
  ];
  for (const [tag, prompt, jobs] of dimensions) {
    add(prompt, [tag]);
    for (const job of jobs.slice(0, 10)) add(`For ${tag}, would you say a ${job} has a job like yours?`, [tag, job]);
  }
  const jobs = [...new Set(dimensions.flatMap(d => d[2]))];
  const candidates = jobs.map((name, i) => ({name, tags: new Set(dimensions.filter(d=>d[2].includes(name)).map(d=>d[0])), prior: 1 + (i % 3)}));
  let state = {phase:'intro', asked:[], answers:[], pool:[...candidates], start:0, seconds:120, name:''};
  let timerId;
  const answerWeight = {"Yes":1,"Probably":.7,"I don't know":.5,"Probably not":.3,"No":0};
  function setMusic(track){for(const a of document.querySelectorAll('audio')){a.pause();a.currentTime=0} if(!soundOn)return;const a=$(track);if(a){a.volume=.35;a.play().catch(()=>{})}}
  let soundOn=true;
  function expression(){const faces=['Let me dust off my tiny detective hat…','Ooh, I’m getting somewhere…','The ladder is doing some maths…','Your job is playing hard to get…','I have a very professional hunch…','Hmm. Suspiciously job-shaped…'];return faces[Math.floor(Math.random()*faces.length)]}
  function showIntro(){ $('stage-label').textContent='A LITTLE GAME ABOUT WHAT YOU DO';$('intro-copy').hidden=false;$('game-copy').hidden=true;$('timer').hidden=true;$('subtitle-overlay').textContent=''; }
  function start(){state={phase:'intro',asked:[],answers:[],pool:[...candidates],start:Date.now(),seconds:120,name:''};$('stage-label').textContent='THE CAREER LADDER IS THINKING';setMusic('music-entry');$('scene').classList.add('zoomed');const words="Hope you don't have to hold your bladder cuz it's time for the Career Ladder".split(' ');const layer=$('subtitle-overlay');layer.replaceChildren();words.forEach((word,i)=>setTimeout(()=>{const span=document.createElement('span');span.textContent=(i?' ':'')+word;layer.append(span);},i*500));setTimeout(()=>{state.phase='hasjob';$('intro-copy').hidden=true;$('game-copy').hidden=false;layer.textContent='';renderQuestion('Do you have a job?','Be honest. The ladder can handle it.','hasjob');},words.length*500+500);}
  function runTimer(){clearInterval(timerId);timerId=setInterval(()=>{state.seconds--;const m=String(Math.floor(state.seconds/60)).padStart(2,'0'),s=String(state.seconds%60).padStart(2,'0');$('timer').textContent=`${m}:${s}`;if(state.seconds<=0){clearInterval(timerId);finishWin('The two minutes are up! You win. Tell me what you do?')}},1000)}
  function renderQuestion(prompt, helper='', type='trait'){state.phase=type;$('expression').textContent=expression();$('question').textContent=prompt;$('helper').textContent=helper;$('answers').replaceChildren();if(type==='name'){showForm();return}const choices=type==='hasjob'?['Yes','No']:type==='guess'?['Yes','No']:choiceLabels;for(const label of choices){const b=document.createElement('button');b.className='answer';b.textContent=label;b.onclick=()=>respond(label);$('answers').append(b)}$('progress-text').textContent=type==='hasjob'?'THE FIRST RUNG':`QUESTION ${state.asked.length+1} · ${candidates.length} POSSIBLE JOBS`;$('progress-bar').style.width=`${Math.min(100,state.asked.length/12*100)}%`;}
  function showForm(){const form=document.createElement('form');form.className='share-form';form.innerHTML='<label>Your job<input name="job" required maxlength="80" placeholder="e.g. marine biologist"></label><label>Your name <span>(optional)</span><input name="name" maxlength="60" placeholder="What should I call you?"></label><button class="primary-button" type="submit">Help the next player <span>↗</span></button><button type="button" class="answer skip-share">Skip sharing</button><p class="form-note">Your job and name are saved only when the site owner configures Supabase. Don’t include anything private.</p>';form.onsubmit=(e)=>{e.preventDefault();const data=new FormData(form);saveContribution(String(data.get('job')).trim(),String(data.get('name')).trim());};form.querySelector('.skip-share').onclick=()=>endWin();$('answers').replaceChildren(form);}
  function respond(label){if(state.phase==='hasjob'){if(label==='No'){renderQuestion('Ahhh! You need a job for this.','Come back when you’ve got one!','stop');$('answers').replaceChildren();const b=document.createElement('button');b.className='primary-button';b.textContent='Try again';b.onclick=()=>{showIntro();};$('answers').append(b);setMusic('music-sad');return}renderQuestion('I’ll guess your job in two minutes.','If I guess it, you lose. If I don’t, you’ll make me cry. Ready?','ready');$('answers').replaceChildren();const b=document.createElement('button');b.className='primary-button';b.textContent='Let’s climb';b.onclick=()=>respond('Yes');$('answers').append(b);return}
    if(state.phase==='ready'){setMusic('music-theme');runTimer();nextQuestion();return} if(state.phase==='guess'){if(label==='Yes'){state.won=false;finishLose();}else{state.pool=state.pool.filter(c=>c.name!==state.guess);nextQuestion()}return}
    state.asked.push(state.current.text);state.answers.push({question:state.current.text,answer:label,tag:state.current.tag});const weight=answerWeight[label];state.pool=state.pool.filter(c=>{const has=c.tags.has(state.current.tag);return weight===.5|| (weight>=.7?has:!has)});state.pool=state.pool.length?state.pool:candidates.filter(c=>!state.asked.includes(c.name));learnedAnswers(state.current.text,label);nextQuestion();}
  async function nextQuestion(){if(state.seconds<=0)return finishWin('The two minutes are up! You win. Tell me what you do?');
    if(supabaseReady&&state.answers.length>=4){const learned=await supa('trusted_job_answers?select=job_name,job_normalized,question_text,answer_value,respondent_count,answer_count');if(learned){const scores=new Map();for(const row of learned){if(row.respondent_count<=3||row.answer_count<3)continue;const match=state.answers.some(a=>a.question===row.question_text&&a.answer===row.answer_value);if(match)scores.set(row.job_name,(scores.get(row.job_name)||0)+1)}const best=[...scores].sort((a,b)=>b[1]-a[1])[0];if(best&&best[1]>=3){state.guess=best[0];renderQuestion(`Is your job ${best[0]}?`,'More than three players taught me that one. Is it you?','guess');return}}}
    const score=(c)=>state.answers.reduce((sum,a)=>sum-Math.abs(answerWeight[a.answer]-(c.tags.has(a.tag)?1:0)),0)+c.prior*.001;const sorted=[...state.pool].sort((a,b)=>score(b)-score(a));const top=sorted[0];if(top&&state.asked.length>=5){state.guess=top.name;renderQuestion(`Is your job ${top.name}?`,'I’m putting my whole ladder on this.','guess');return}if(!state.pool.length||state.asked.length>=dimensions.length){finishWin('Alright, you just win! Tell me what it is?');return}const dimension=dimensions[state.asked.length%dimensions.length];const prompt=bank.find(q=>q.text===dimension[1]);state.current={text:prompt.text,tag:dimension[0]};renderQuestion(prompt.text,'Pick the answer that feels closest.');}
  function finishLose(){clearInterval(timerId);state.phase='lose';$('stage-label').textContent='THE LADDER GOT THERE FIRST';$('expression').textContent='I knew it!';$('question').textContent=`You're a ${state.guess}!`;$('helper').textContent='The ladder wins this round. Fancy a rematch?';$('answers').replaceChildren();const b=document.createElement('button');b.className='primary-button';b.textContent='Play again';b.onclick=()=>showIntro();$('answers').append(b);setMusic('music-happy')}
  function finishWin(msg){clearInterval(timerId);state.phase='name';$('stage-label').textContent='A JOB WELL DONE';$('expression').textContent='You got past me!';$('question').textContent=msg;$('helper').textContent='Tell me your job to teach the next ladder climber.';setMusic('music-sad');showForm()}
  function endWin(){clearInterval(timerId);state.phase='done';$('stage-label').textContent='THANKS FOR PLAYING';$('expression').textContent='The ladder will remember this.';$('question').textContent='Thanks for climbing!';$('helper').textContent='Your answers were not saved. Come back for another round.';$('answers').replaceChildren();const b=document.createElement('button');b.className='primary-button';b.textContent='Play again';b.onclick=()=>showIntro();$('answers').append(b)}
  async function supa(path,method='GET',body,prefer='return=minimal'){if(!supabaseReady)return null;try{const r=await fetch(`${config.supabaseUrl.replace(/\/$/,'')}/rest/v1/${path}`,{method,headers:{apikey:config.supabaseAnonKey,Authorization:`Bearer ${config.supabaseAnonKey}`,...(body?{'Content-Type':'application/json','Prefer':prefer}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(`Supabase ${r.status}`);return r.status===204?[]:await r.json()}catch(e){console.warn('Career Ladder database is not connected:',e);return null}}
  async function learnedAnswers(question,answer){if(!supabaseReady)return;await supa('answer_history','POST',{question_text:question,answer_value:answer,session_id:sessionId});}
  const sessionId=crypto.randomUUID?.()||String(Date.now());
  const playerId=(()=>{try{let id=localStorage.getItem('career-ladder-player');if(!id){id=crypto.randomUUID?.()||String(Date.now())+Math.random();localStorage.setItem('career-ladder-player',id)}return id}catch{return crypto.randomUUID?.()||String(Date.now())}})();
  async function saveContribution(job,name){if(!supabaseReady){$('helper').textContent='Supabase is not connected yet, so I can’t save this. You can still play again!';const b=document.createElement('button');b.className='answer';b.textContent='Finish without saving';b.onclick=endWin;$('answers').append(b);return}const norm=job.toLowerCase().trim();await supa('job_suggestions?on_conflict=job_normalized,player_id','POST',{job_name:job,job_normalized:norm,player_id:playerId,player_name:name||null,answers:state.answers},'resolution=ignore-duplicates,return=minimal');const rows=await supa(`job_consensus?job_normalized=eq.${encodeURIComponent(norm)}&select=respondent_count`);const count=rows?.[0]?.respondent_count||0;$('question').textContent=count>3?'The ladder has learned a new job!':`Thanks! ${Math.max(0,4-count)} more player${4-count===1?'':'s'} needed before I can trust this job.`;$('helper').textContent='Your clue will help the next player. The game keeps the answers for future rounds.';state.phase='done';$('answers').replaceChildren();const b=document.createElement('button');b.className='primary-button';b.textContent='Play again';b.onclick=()=>showIntro();$('answers').append(b);setMusic('music-happy')}
  $('start-button').onclick=start;$('year').textContent=new Date().getFullYear();$('sound-toggle').onclick=()=>{soundOn=!soundOn;$('sound-toggle').innerHTML=soundOn?'♫ <span>Sound on</span>':'♫ <span>Sound off</span>';if(soundOn&&state.phase!=='intro')setMusic('music-entry');else{for(const a of document.querySelectorAll('audio'))a.pause()}};showIntro();
  // The script builds 200+ distinct prompts. Generic prompts are presented first; job-specific ones remain available as the pool narrows.
  window.CAREER_LADDER_QUESTION_COUNT=bank.length;
})();
